In [1]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns 
import statistics as sts 
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score,recall_score
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler,OneHotEncoder

In [2]:
#Data Collection last few months shravan data
dataFrame1=pd.read_csv(r"C:\Shravan\PythonPratice\supervised\MyObservabilityQueue.csv",encoding_errors='ignore')

In [3]:
#Data information
dataFrame1.info()
dataFrame1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              607 non-null    int64
 1   Work Item Type  607 non-null    object
 2   Title           607 non-null    object
 3   Assigned To     607 non-null    object
 4   State           607 non-null    object
 5   Tags            555 non-null    object
 6   Created By      607 non-null    object
 7   Actual Time     266 non-null    float64
 8   Closed Status   0 non-null      float64
dtypes: float64(2), int64(1), object(6)
memory usage: 42.8+ KB

                 ID  Actual Time  Closed Status
count    607.000000   266.000000            0.0
mean   16153.566722     3.112782            NaN
std      929.694283     2.978613            NaN
min    13695.000000     0.000000            NaN
25%    15403.000000     1.000000            NaN
50%    16296.000000     2.000000            NaN
75%    16823.500000     4.000000            NaN
max    18029.000000    24.000000            NaN

In [4]:
#Missing and null values checks
dataFrame1.isna().sum()  # missing data

ID                  0
Work Item Type      0
Title               0
Assigned To         0
State               0
Tags               52
Created By          0
Actual Time       341
Closed Status     607
dtype: int64

In [5]:
dataFrame1.isnull().sum()  # find the null data

ID                  0
Work Item Type      0
Title               0
Assigned To         0
State               0
Tags               52
Created By          0
Actual Time       341
Closed Status     607
dtype: int64

In [6]:
#sample data
dataFrame1.sample(10)

,ID,Work Item Type,Title,Assigned To,State,Tags,Created By,Actual Time,Closed Status
132,15261,Task,Transfomrtion deployements,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Global; Observability; S25-07; S25-08,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,1.0,NaN
247,15818,Task,Logstash user creation,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Removed,NaN,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,1.0,NaN
144,15302,Product Backlog Item,RITM0547669- Tristan || eESB,Mohammed Arbaaz Saber <BVU4@it.eurofinseu.com>,Done,S25-07,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,NaN,NaN
428,16673,Task,Tentacle ports followups and checks,Alluri Sreenivasulu <Y4UH@it.eurofinseu.com>,Done,S25-16,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,3.0,NaN
365,16487,Task,Support (update URL script),Sayed Ulfath Hussain S Bellary <A9JB@it.eurofi...,Done,NaN,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,4.0,NaN
81,15070,Product Backlog Item,Servicenow - Tickets : INC3266971,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,NaN,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,NaN,NaN
29,14668,Product Backlog Item,INC3056578 - eESB,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Global; Observability; S25-01,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,NaN,NaN
51,14901,Product Backlog Item,Servicenow tickets: || RITM0568108,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Global; Observability; S25-03,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,NaN,NaN
166,15502,Product Backlog Item,RITM0613217 - userid - 1004,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Global; Observability; S25-08,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,NaN,NaN
344,16367,Product Backlog Item,Service now tickets - RITM0642999 - ComLIMS - ...,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Global; Observability; S25-13,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,NaN,NaN

In [7]:
#filling data