In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import statistics as sts

In [3]:
df1=pd.read_csv(r"F:\ExternalSoftwares\Spyder\PraticeZipfiles\archive\Employee.csv",encoding_errors='ignore')

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          10000 non-null  int64
 1   First Name     10000 non-null  object
 2   Last Name      10000 non-null  object
 3   Sex            10000 non-null  object
 4   Email          10000 non-null  object
 5   Phone          10000 non-null  object
 6   Date of birth  10000 non-null  object
 7   Job Title      10000 non-null  object
dtypes: int64(1), object(7)
memory usage: 625.1+ KB

In [9]:
df1.select_dtypes(include=['object']).columns

Index(['First Name', 'Last Name', 'Sex', 'Email', 'Phone', 'Date of birth',
       'Job Title'],
      dtype='object')

In [4]:
df1.head(20)

,Index,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,Sara,Mcguire,Female,tsharp@example.net,(971)643-6089x9160,17-08-21,"Editor, commissioning"
1,2,Alisha,Hebert,Male,vincentgarrett@example.net,+1-114-355-1841x78347,28-06-69,Broadcast engineer
2,3,Gwendolyn,Sheppard,Male,mercadojonathan@example.com,9017807728,25-09-15,Industrial buyer
3,4,Kristine,Mccann,Female,lindsay55@example.com,+1-607-333-9911x59088,27-07-78,Multimedia specialist
4,5,Bobby,Pittman,Female,blevinsmorgan@example.com,3739847538,17-11-89,Planning and development surveyor
5,6,Calvin,Ramsey,Female,loretta85@example.com,001-314-829-5014x1792,31-08-17,Therapeutic radiographer
6,7,Collin,Allison,Male,yvaughn@example.net,(314)591-7413,21-11-79,Administrator
7,8,Nicholas,Branch,Male,greerjimmy@example.net,-7199,21-01-06,Fisheries officer
8,9,Emma,Robinson,Female,charleshiggins@example.org,166-234-6882x7457,19-03-09,Haematologist
9,10,Pedro,Cordova,Male,leslie08@example.com,(389)824-3204x8287,17-06-08,Phytotherapist
10,11,Jean,Aguilar,Male,raymond24@example.org,(285)029-1604x5466,28-10-78,"Engineer, control and instrumentation"
11,12,Dwayne,Hutchinson,Female,preston28@example.net,(233)811-1749x417,22-06-14,"Teacher, early years/pre"
12,13,Bradley,Velazquez,Male,joycejay@example.net,(831)049-2030,23-12-06,Airline pilot
13,14,Samantha,Moon,Male,wesleymullins@example.net,7788378816,21-06-78,Intelligence analyst
14,15,Clayton,Erickson,Male,nterry@example.net,990-374-0521x33156,07-02-59,Paediatric nurse
15,16,Bradley,Bright,Female,devinherman@example.net,2534420151,27-01-92,Fitness centre manager
16,17,Ernest,Maynard,Male,tommywoodard@example.com,355-863-2311x6315,23-11-17,"Accountant, chartered certified"
17,18,Joe,Larsen,Female,brianna43@example.org,(566)667-8566x109,18-06-09,Geographical information systems officer
18,19,Alfred,Barrera,Female,kristina40@example.net,4735530004,13-11-24,"Administrator, charities/voluntary organisations"
19,20,Jon,Wagner,Female,meagan99@example.org,001-940-671-0693x345,06-01-34,"Engineer, aeronautical"

In [ ]:
df1.columns

Index(['MovieID', 'Title', 'Genre', 'ReleaseYear', 'ReleaseDate', 'Country',
       'BudgetUSD', 'US_BoxOfficeUSD', 'Global_BoxOfficeUSD',
       'Opening_Day_SalesUSD', 'One_Week_SalesUSD', 'IMDbRating',
       'RottenTomatoesScore', 'NumVotesIMDb', 'NumVotesRT', 'Director',
       'LeadActor'],
      dtype='object')

In [ ]:
df1['Genre'].value_counts()

Genre
Drama          250018
Comedy         199832
Action         150131
Thriller       100071
Romance        100021
Horror         100010
Documentary     50114
Sci-Fi          49802
Name: count, dtype: int64

In [ ]:
df1["Genre_status_numeric"]=df1['Genre'].map({'Drama':1,'Comedy':2,'Action':3,'Thriller':4,'Romance':5,'Horror':6,'Documentary':7,'Sci-Fi':8})

In [ ]:
df1.head(10)

,MovieID,Title,Genre,ReleaseYear,ReleaseDate,Country,BudgetUSD,US_BoxOfficeUSD,Global_BoxOfficeUSD,Opening_Day_SalesUSD,One_Week_SalesUSD,IMDbRating,RottenTomatoesScore,NumVotesIMDb,NumVotesRT,Director,LeadActor,Genre_status_numeric
0,1,Might toward capital,Comedy,2003,28-09-2003,China,6577427.79,6613685.82,15472035.66,1778530.85,3034053.32,6.2,58,7865,10596,Kristina Moore,Brian Mccormick,2
1,2,He however experience,Comedy,1988,14-02-1988,USA,1883810.10,1930949.15,3637731.12,247115.74,831828.84,5.2,44,1708,220,Benjamin Hudson,Ashley Pena,2
2,3,Star responsibility politics,Comedy,1971,02-11-1971,USA,2468079.29,4186694.69,7165111.24,878453.95,2171405.93,5.5,55,4678,7805,Kayla Young,Alexander Haley,2
3,4,Exactly live,Comedy,1998,06-08-1998,USA,1447311.46,2023683.92,4373820.26,570657.72,898886.01,7.3,87,2467,1751,Michael Ross,Patrick Barnett,2
4,5,Focus improve especially,Documentary,2021,17-12-2021,India,900915.86,2129629.10,3113017.38,361189.37,861775.91,6.1,67,5555,697,Faith Franklin,Duane Fletcher DDS,7
5,6,Deal reveal fine,Drama,1996,09-05-1996,USA,6356058.11,6790420.62,12332192.70,1877251.88,3681524.22,8.9,100,362,229,Thomas Peterson,Carolyn Calhoun,1
6,7,Drug when,Comedy,1991,24-09-1991,USA,30881640.04,35569499.73,61633322.70,5771559.63,21305870.04,3.6,39,556,98,Maria Lane,Melissa Cain,2
7,8,Almost option of,Horror,1990,04-08-1990,USA,5249748.92,3569563.24,6059156.85,429972.59,1513066.66,7.3,75,283,1219,Diane Skinner,Catherine Willis,6
8,9,Film about training,Drama,1983,12-03-1983,USA,4746218.15,6361493.82,9506139.90,1612321.12,2977114.88,6.9,69,1041,1467,Albert Phillips,Ashley Reeves,1
9,10,Begin difficult world,Documentary,2005,06-09-2005,USA,1354686.21,3837061.91,6747065.42,440667.37,2031776.94,8.4,87,10079,514,Francisco Ford,Richard Miller,7

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999999 entries, 0 to 999998
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   MovieID               999999 non-null  int64
 1   Title                 999999 non-null  object
 2   Genre                 999999 non-null  object
 3   ReleaseYear           999999 non-null  int64
 4   ReleaseDate           999999 non-null  object
 5   Country               999999 non-null  object
 6   BudgetUSD             999999 non-null  float64
 7   US_BoxOfficeUSD       999999 non-null  float64
 8   Global_BoxOfficeUSD   999999 non-null  float64
 9   Opening_Day_SalesUSD  999999 non-null  float64
 10  One_Week_SalesUSD     999999 non-null  float64
 11  IMDbRating            999999 non-null  float64
 12  RottenTomatoesScore   999999 non-null  int64
 13  NumVotesIMDb          999999 non-null  int64
 14  NumVotesRT            999999 non-null  int64
 15  Director              999999 non-null  object
 16  LeadActor             999999 non-null  object
 17  Genre_status_numeric  999999 non-null  int64
dtypes: float64(6), int64(6), object(6)
memory usage: 137.3+ MB

In [ ]:
from sklearn.preprocessing import (
    LabelEncoder,OrdinalEncoder,OneHotEncoder
)

In [ ]:
data={
    'a':[1,2,3,4,5],
    'b':['cat','rat','pulli','lion','cock']
}
pdf1=pd.DataFrame(data)

https://colab.research.google.com/drive/1D7_9EQuCzhWYqzicr9WEtnCL4NVa3yEU?usp=sharing
https://colab.research.google.com/drive/1_LNCoblRtwJE8RiHIgVW_NzZ9ZBXYdeT?usp=sharing
https://colab.research.google.com/drive/14DHUcOY8oe9vtYZRvvUIA72YajasM5uJ?usp=sharing
https://colab.research.google.com/drive/1JXpdo3GExMtgMQ3FF6WYXfsxVfTf5GEw?usp=sharing