In [3]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder
from category_encoders import CountEncoder,BinaryEncoder,TargetEncoder
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt 
import seaborn as sns

In [4]:
s1=pd.read_csv(r"F:\ExternalSoftwares\pythoncodes\supervised\SupervisedLearning\StudentsPerformance.csv",encoding_errors='ignore')

In [5]:
s1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [10]:
s1.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [6]:
s1.ndim

2

In [7]:
s1.shape

(1000, 8)

In [8]:
s1.size

8000

In [11]:
s1.sample(10)

     gender race/ethnicity  ... reading score writing score
503  female        group E  ...            89            92
586  female        group A  ...            73            73
619    male        group C  ...            73            68
630    male        group D  ...            64            70
144    male        group D  ...            73            78
915  female        group E  ...            70            66
595  female        group C  ...            79            72
663  female        group C  ...            69            67
528  female        group D  ...            41            47
494  female        group B  ...            64            68

[10 rows x 8 columns]