In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder
from category_encoders import TargetEncoder,CountEncoder,BinaryEncoder,SummaryEncoder,SumEncoder,GrayEncoder

In [ ]:
data = {
    'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red', 'Green', 'Blue', 'Red'],
    'Size': ['S', 'M', 'L', 'M', 'S', 'XL', 'L', 'M'],
    'City': ['New York', 'London', 'Paris', 'London', 'New York', 'Tokyo', 'Paris', 'New York'],
    'Purchased': [1, 0, 1, 0, 1, 0, 1, 0] # This will be our target variable for some encoders
}

In [10]:
df1=pd.DataFrame(data)

df1

   Color Size      City  Purchased
0    Red    S  New York          1
1   Blue    M    London          0
2  Green    L     Paris          1
3   Blue    M    London          0
4    Red    S  New York          1
5  Green   XL     Tokyo          0
6   Blue    L     Paris          1
7    Red    M  New York          0

##lable encoding used in 

nomial data 
No order varubales
returns the int values
Unique integer to each class for column
if target variable is spam/not like that such conditions like y variables

In [14]:
label_encoding=LabelEncoder()
df1['color_label_encoded']=label_encoding.fit_transform(df1['Color'])
print(df1[['Color','color_label_encoded']])

   Color  color_label_encoded
0    Red                    2
1   Blue                    0
2  Green                    1
3   Blue                    0
4    Red                    2
5  Green                    1
6   Blue                    0
7    Red                    2

##ordinal encoding
-> When order is matter
-> Specially for features 
-> returns the float value
-> customised order classes data

In [32]:
orders=['S','M','XL','L']

ordinal_encode=OrdinalEncoder(categories=[orders],handle_unknown='use_encoded_value',unknown_value=10,encoded_missing_value=12)
df1['size_encoded']=ordinal_encode.fit_transform(df1[['Size']]).astype(int)
print(df1[['Size','size_encoded']])

  Size  size_encoded
0    S             0
1    M             1
2    L             3
3    M             1
4    S             0
5   XL             2
6    L             3
7    M             1

##one hot encoder
 --> 3 ways 
      -> sklearn
      -> category_encodrs
      -> using pandas
--> useed for classficications

In [65]:
#using sklearn

cities=['New York', 'London', 'Paris', 'Tokyo']
Ohe=OneHotEncoder(categories=[cities],handle_unknown='ignore',sparse_output=False,drop='first')

cities_ohe_encoded=Ohe.fit_transform(df1[['City']])
print(cities_ohe_encoded.astype(int))

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 0]]

In [78]:
#using pandas

p1=pd.get_dummies(data=df1,columns=['City'],prefix='ohe',dtype='int')
p1

,Color,Size,Purchased,color_label_encoded,size_encoded,ohe_London,ohe_New York,ohe_Paris,ohe_Tokyo
0,Red,S,1,2,0,0,1,0,0
1,Blue,M,0,0,1,1,0,0,0
2,Green,L,1,1,3,0,0,1,0
3,Blue,M,0,0,1,1,0,0,0
4,Red,S,1,2,0,0,1,0,0
5,Green,XL,0,1,2,0,0,0,1
6,Blue,L,1,0,3,0,0,1,0
7,Red,M,0,2,1,0,1,0,0

In [ ]:
import category_encoders as ce

ce1=ce.OneHotEncoder(cols=[df1['City']],use_cat_names='city_')

TypeError: unhashable type: 'Series'

In [11]:

df1.columns

Index(['Color', 'Size', 'City', 'Purchased'], dtype='object')

In [35]:
df1['City'].value_counts().to_dict().keys()

dict_keys(['New York', 'London', 'Paris', 'Tokyo'])